[build]
command = "npm install && NEXT_TELEMETRY_DISABLED=1 NODE_ENV=production npm run build"
output_directory = ".next/standalone"

[site]
bucket = ".next/standalone"

[env.production]
name = "inbest-frontend-demo"
compatibility_date = "2024-01-01"
node_compat = true 