name = "inbest-frontend-demo"
compatibility_date = "2024-01-01"
node_compat = true

[build]
command = "pnpm install && NEXT_TELEMETRY_DISABLED=1 NODE_ENV=production pnpm run build && cp _worker.js dist/standalone/"

[build.upload]
format = "directory"

[site]
bucket = "dist/standalone"

[pages]
pages_build_output_dir = "dist/standalone"

[[build.upload.rules]]
type = "CompiledJavaScript"
globs = ["**/*.js"] 